### ISSUE TITLE
"Other examples" links lead to 404

### ISSUE THREAD

**Issue by shoooe** [ramosbugs/oauth2-rs#101]
In the library's docs, section ["Other examples"](https://docs.rs/oauth2/3.0.0/oauth2/#other-examples) all links seem to lead to a 404.

**Comment by ramosbugs** [comment]
ah, `master` needs to be updated to `main`:
https://github.com/ramosbugs/oauth2-rs/blob/c82b14210e991c1f45368de83aae79acf103e162/src/lib.rs#L473-L476
