### ISSUE TITLE
Device Flow/Device Authorization Grant Support

### ISSUE THREAD

**Issue by smolck** [ramosbugs/oauth2-rs#105]
Is it possible to do this with this library? If not, could support for this flow be added?

https://oauth.net/2/device-flow/

**Comment by ramosbugs** [comment]
The device flow isn't currently supported, but it would be a nice enhancement to this crate.

Adding support would require adding methods for both the Device Authorization request and the Device Access Token request. The former uses a new endpoint and can be supported by following similar steps to the ones I outlined in #97 for the Token Introspection endpoint. The Device Access Token request reuses the existing token endpoint, so we just need to add a `Client::exchange_device_code` method.

I'd happily accept a PR that does this (with corresponding test coverage).

**Comment by maxdymond** [comment]
FWIW I'm working on this at the moment. So far the interface is like this (running against a Google OAuth2 application)

```rust
    // Set up the config for the Google OAuth2 process.
    let device_client = BasicClient::new(
        google_client_id.clone(),
        Some(google_client_secret.clone()),
        auth_url.clone(),
        Some(token_url.clone()),
    )
    .set_device_authorization_url(device_auth_url);

    // Request the set of codes from the Device Authorization endpoint.
    let details = device_client
        .exchange_device_code()
        .add_scope(Scope::new("profile".to_string()))
        .request_codes(http_client)
        .expect("Failed to request codes from device auth endpoint");

    // Display the URL and user-code.
    println!(
        "Open this URL in your browser:\n{}\nand enter the code: {}",
        details.verification_uri().to_string(),
        details.user_code().to_string()
    );

    // Now poll for the token
    let token = BasicClient::new(
        google_client_id,
        Some(google_client_secret),
        auth_url,
        Some(token_url),
    )
    .set_device_authorization_details(details)
    .exchange_device_access_token()
    .request(http_client)
    .expect("Failed to request access token from token auth endpoint");

    println!("Google returned the following token:\n{:?}\n", token);
```

I've written the first half (up to and including the displaying of codes to the user), and now I'm working on how to repeatedly poll the endpoint.
