### ISSUE TITLE
HTTP Basic Auth method

### ISSUE THREAD

**Issue by Epse** [ramosbugs/oauth2-rs#116]
I am authenticating with an endpoint which requires client id and secret to be provided via HTTP Basic Auth, with the `Authorization` header set to `Basic base64(clientid:clientsecret)` (thus using client credentials method) using HTTP GET. Is this supported by the library? I can't figure it out from the documentation.

Thanks for the work on this beautiful library!

**Comment by ramosbugs** [comment]
The [`Client::set_auth_type`](https://docs.rs/oauth2/4.0.0-alpha.2/oauth2/struct.Client.html#method.set_auth_type) method controls whether the client credentials are sent in the `Authorization` header or the request body. The former is already the default.

The [`Client::exchange_client_credentials`](https://docs.rs/oauth2/4.0.0-alpha.2/oauth2/struct.Client.html#method.exchange_client_credentials) method implements the client credentials flow, using whichever auth method is configured for the `Client`.

**Comment by Epse** [comment]
Sorry if I wasn't clear enough, but the request also needs to be sent using GET, a glance through the code shows me that is in fact hardcoded. I don't know how to best add this as an option, else I'd probably make a PR.
