### ISSUE TITLE
Add ureq http provider

### ISSUE THREAD

**Issue by Cogitri** [ramosbugs/oauth2-rs#119]
Hello,

I've recently started using oauth2-rs for my application (and it works nicely), but I'm using ureq instead of curl to cut the dependency on that. Would you be interested in me upstreaming that or should users just implement the `http_client` method themselves for ureq (it's only like ~40 LOC)?

**Comment by ramosbugs** [comment]
hey @Cogitri, I don't have any experience with ureq, but I'd be willing to merge a patch if you want to upstream it. just be sure to put it behind a (non-default) feature flag like the reqwest and curl clients. hopefully this won't introduce any versioning issues down the road!
