### ISSUE TITLE
Discord Example

### ISSUE THREAD

**Issue by Jackbaude** [ramosbugs/oauth2-rs#124]
A discord example would be greatly appreciated!

**Comment by ramosbugs** [comment]
does Discord have any quirks that would merit adding (and maintaining) another example?

**Comment by Jackbaude** [comment]
Guess not but it would be nice to have and see. Here is documentation on it
[https://discord.com/developers/docs/topics/oauth2](https://discord.com/developers/docs/topics/oauth2)

**Comment by ramosbugs** [comment]
sorry, I don't provide free consulting services
