### ISSUE TITLE
Can't implement From<RequestTokenError> Becaus trait bound std::error:Error not met

### ISSUE THREAD

**Issue by Adenylatcyclase** [ramosbugs/oauth2-rs#132]
Hi I am trying to consume a RequestTokenError
`impl<E: Into<BoxError>> From<E> for Error {
    fn from(e: E) -> Self {
        Error::Error{inner: Into::into(e)}
    }
}`
wher BoxError is `type BoxError = Box<dyn StdError + Send + Sync>;`
Even though the docs say that It does implement Error my compiler says otherwise.
If I try to implement From for the TequestTokenError<Error, ErrorResponse> the compiler complains about overlapping implementations.

I tried using anyhow but get the same error

> 148 |             .request(http_client)?;
>     |                                  ^ the trait `StdError` is not implemented for `RequestTokenError<oauth2::reqwest::Error<reqwest::error::Error>, StandardErrorResponse<BasicErrorResponseType>>`
>     |
>     = note: required because of the requirements on the impl of `From<RequestTokenError<oauth2::reqwest::Error<reqwest::error::Error>, StandardErrorResponse<BasicErrorResponseType>>>` for `anyhow::Error`
>     = note: required by `std::convert::From::from`

StdError is just std::error::Error

**Comment by ramosbugs** [comment]
which version are you using? in the 3.x release, `RequestTokenError` implements `failure::Fail` instead of `std::error::Error`. in 4.x (which is an "alpha" to allow for further breaking API changes, but should be safe to use in production), it implements `std::error::Error`.

**Comment by Adenylatcyclase** [comment]
thank you. that has solved my problem.
was using 3.0.0 but probably looking at the wrong doc version.
