### ISSUE TITLE
consider adding Send + Sync to reqwest::Error

### ISSUE THREAD

**Issue by Emilgardis** [ramosbugs/oauth2-rs#137]
https://github.com/ramosbugs/oauth2-rs/blob/7c10cf07feb9538f9cc66dcb457bd36fbb1ca864/src/reqwest.rs#L3-L10

This should make the error more correct, would be great if it could be added in time for 4.0.0

**Comment by ramosbugs** [comment]
hmm does this affect anything? the concrete types should already be `Send + Sync` once a specific error type (e.g. from reqwest) is substituted. adding additional trait bounds shouldn't affect the client code but might preclude future HTTP clients that don't have thread-safe error types. I think it's preferable to omit unnecessary trait bounds.

**Comment by Emilgardis** [comment]
I think you are correct, this could prohibit future clients.

**Comment by Emilgardis** [comment]
> hmm does this affect anything? the concrete types should already be `Send + Sync` once a specific error type (e.g. from reqwest) is substituted.

I'm using this error as a generic, and need the error to be Send and Sync, my solution is to specify that the whole type needs to be Send + Sync. It works, but woukd want to be more specific

https://github.com/Emilgardis/twitch_oauth2/blob/0eccb58cf971897ee422e7d98886180b1aa594d2/src/tokens/errors.rs#L6-L11

**Comment by ramosbugs** [comment]
in that scenario, I think you can do `RequestTokenError<oauth2::reqwest::Error<T>, ...>` and then specify the desired bounds on T to avoid making all of RE `Send + Sync`
