### ISSUE TITLE
Q: How to get token data out of token response?

### ISSUE THREAD

**Issue by Natureshadow** [ramosbugs/oauth2-rs#140]
Hi,

*if this is not the expected place to ask questions, please point me to a (freely accessible) channel where questions are on-topic*

I am trying to extract the access token and refresh token as strings from a token response, like at the end of any example, and looking at the docs at: https://docs.rs/oauth2/4.0.0/oauth2/trait.TokenResponse.html

However, all the fields described here are private.

How would I get to the access token, e.g. to use it in an `Authorization` header in some API request I want to do using the token?

Thanks!

**Comment by ramosbugs** [comment]
`StandardTokenResponse` is the struct that stores the (private) fields, while `TokenResponse` is the trait that `StandardTokenResponse` implements and which provides the public methods for accessing those fields. As long as the `TokenResponse` trait has been imported, you should be able to call those methods to access the corresponding fields, as shown in the examples. Hope that helps!

**Comment by Natureshadow** [comment]
Yep, got it now. Importing the trait did the trick.

I am still getting used to the concept of traits…
