### ISSUE TITLE
http2 error: protocol error: endpoint requires HTTP/1.1

### ISSUE THREAD

**Issue by adrosa** [ramosbugs/oauth2-rs#150]
Hello I am trying to use your library to authenticate with AAD. Any thoughts on how to have it use http/1.1

**Comment by ramosbugs** [comment]
Hey @adrosa, the [docs](https://docs.rs/oauth2/4.0.0/oauth2/#importing-oauth2-selecting-an-http-client-interface) describe the various options for HTTP clients, including the ability for users to provide their own custom clients to meet their needs.
