### ISSUE TITLE
Discord exchange_code request returning invalid_client

### ISSUE THREAD

**Issue by Stumblinbear** [ramosbugs/oauth2-rs#160]
Using `exchange_code` against the Discord OAuth endpoint results in a response of `invalid_client`. Outputting the `exchange_code` return value gives:

```
CodeTokenRequest {
  auth_type: RequestBody,
  client_id: ClientId("-redacted-"),
  client_secret: Some(ClientSecret([redacted])),
  code: AuthorizationCode([redacted]),
  extra_params: [],
  pkce_verifier: None,
  token_url: Some(TokenUrl("https://discord.com/api/oauth2/token")),
  redirect_url: Some(RedirectUrl("http://localhost:3001/oauth/discord")),
  _phantom: PhantomData
}
```

Which appears to all be correct. I've yet to inspect the request body itself, because the function is private.

However, it still fails. Note that the same code works against Google's (and Github's) OAuth API, it's just Discord that fails, leading me to believe it's a library implementation oversight, or Discord is doing something non-standard.

**Comment by boardmaster357** [comment]
I am getting a similar error, except I am using exchange_client_credentials and the intel api. I have working code in Python that connects to Intel, so it must be a problem with the Rust code. Any ideas how to fix this?

**Comment by boardmaster357** [comment]
The problem with the Intel API is that the client_secret has special symbols, which this library url encodes. Intel expects them to be not url encoded which is how the Python library apparently works. The library mentions in the comments that url encoding is the standard, so it appears that the library is correct. Maybe Discord is not expecting properly url encoded special symbols.

**Comment by tistatos** [comment]
I have a similar issue to this, with ticktick.com

**Comment by hcrohland** [comment]
I am having the same problem with www.strava.com

I get a valid response when using "application/x-www-form-urlencoded" for the request, which is demanded by the standard according to https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.3

If I use application/json I get the error I am getting from oauth2-rs. Does the library use the wrong post format "application/json"?

**Comment by ramosbugs** [comment]
> I am having the same problem with [www.strava.com](http://www.strava.com)
> 
> I get a valid response when using "application/x-www-form-urlencoded" for the request, which is demanded by the standard according to https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.3
> 
> If I use application/json I get the error I am getting from oauth2-rs. Does the library use the wrong post format "application/json"?

This crate adheres to the spec and sets `Content-type: application/x-www-form-urlencoded` in its endpoints requests here:
https://github.com/ramosbugs/oauth2-rs/blob/00fa30b336a8b3c9c4c900ae3ccba371459c0ac8/src/lib.rs#L1959-L1962

**Comment by ramosbugs** [comment]
I'm going to close this issue because it's turning into a catch-all of various misuses and/or providers not following the spec, none of which has been traced back to a bug in the crate itself. If anyone finds an actual bug in the crate, please open a new issue with all the required details. I don't have the bandwidth to provide direct user support except to major [sponsors](https://github.com/sponsors/ramosbugs).
