### ISSUE TITLE
Approach for debugging ExtraTokenFields

### ISSUE THREAD

**Issue by JulianRuiseco** [ramosbugs/oauth2-rs#164]
I am trying to auth into a service that is supposed to contain a set of additional fields.

However, when I go through the usual process of exchanging the token, the deserialization has already been done. 

Is there a way to capture the response from the server and log it before the deserialization has been done?

```
let token_res = client
                .exchange_code(code)
                .set_pkce_verifier(pkce_verifier)
                .request(http_client);
```

**Comment by JulianRuiseco** [comment]
Yeah, the fields are absolutely in the token. Not really sure why it refuses to deserialize them.

**Comment by ramosbugs** [comment]
are you seeing a deserialization error? the error output this crate has that's annotated by `serde_path_to_error` should help to identify the issue

**Comment by JulianRuiseco** [comment]
@ramosbugs Hey. I did end up puzzling  that out and it wS helpful.  Turns out  the fields I wanted  were encoded into the access_token. I used the jasonwebtoken crate to deserialize.
