### ISSUE TITLE
Could you make Client's client id as pub?

### ISSUE THREAD

**Issue by tomocrafter** [ramosbugs/oauth2-rs#165]
Since Twitter's OAuth2 requires the client ID in the parameter as well, even though the urlencoded client ID is already included in the request body ( https://github.com/ramosbugs/oauth2-rs/blob/main/src/lib.rs#L1935 ), I would like Client struct to exposes the client_id parameter as pub or adding pub function.

I made little workaround to use this great library on twitter oauth2 as like
```Rust
// Get an auth token
let token = oauth_client
    .exchange_code(code)
    .add_extra_param("client_id", env::var("TWITTER_CLIENT_ID").context("Missing TWITTER_CLIENT_ID!").unwrap()) // Here!
    .set_pkce_verifier(session.get("pkce_code_verifier").unwrap())
    .request_async(async_http_client)
    .await
    .unwrap();
```

**Comment by multimeric** [comment]
Seconded, it would be nice for this any potentially the other fields to be public, just for convenience. But particularly for Twitter for the reason you have stated.

**Comment by ramosbugs** [comment]
Sounds reasonable. Feel free to submit a PR!
