### ISSUE TITLE
Design question: Implementing Serde's Deserialize for some of the types

### ISSUE THREAD

**Issue by EdmundsEcho** [ramosbugs/oauth2-rs#169]
I'm just starting to use this library to authenticate users using the "usual suspects" of providers (google, facebook, github etc...).  To do so, I'm thinking I will need to initialize a collection of `BasicClient` types (a `Client`).  The specifics for each would be hosted in a configuration file.  An efficient way to do so would be to `Deserialize` the `BasicClient` values from the configuration.

What is the reason for not implementing the Serde traits for something like `BasicClient`?

**Comment by ramosbugs** [comment]
hey @EdmundsEcho, I'd prefer not to make the client (de)serializable to avoid committing to a new (implicit) API that would need to remain backward compatible. The fields within `Client` are all private, and I think serde implementations make the most sense on POD (plain old data) types with public fields. The `Client` functions as an interactive abstraction whose internal state is opaque.

Also, in cases where a `ClientSecret` is being used, I have concerns about the `Serialize` implementation making it too easy to accidentally leak the secret into logs. This is in contrast to the `Client`'s `Debug` implementation, which doesn't print the secret.

**Comment by EdmundsEcho** [comment]
Thank you.  This is helpful, and generally so to augment how I'm thinking about my designs and the use of this crate.   

This all relates to how much it makes sense to use/reuse an instance of a `Client`.  For a given instance where `client_id` is set, it seems reasonable to reuse the instance for different users.  Per the design, the redirect urls are `set` "on the fly".

The next piece of the puzzle seems to be deciding on how to host the state required to subsequently validate the response using pkce or state challenge:

```rust
// a component of the redirect url
let (pkce_code_challenge, pkce_code_verifier) = PkceCodeChallenge::new_random_sha256();

// ... the handler for the redirect url needs to access the pkce_code_verifier

```
Is that about right?


In order to

**Comment by ramosbugs** [comment]
yup. the Google example hopefully helps illustrate this: https://github.com/ramosbugs/oauth2-rs/blob/c3a0f8445672c324b35de4d6be01826f5ac162c4/examples/google.rs#L59-L138

**Comment by EdmundsEcho** [comment]
In the google example, we have the following:

```rust
let (pkce_code_challenge, pkce_code_verifier) = PkceCodeChallenge::new_random_sha256(); 
 ```

Is there a reason not to store the  `pkce_code_verifier` in the browser (instead of using the shared state used in the example)?

**Comment by EdmundsEcho** [comment]
I'm getting closer.  Given that for now, the pkce challenge must be kept in a server session, and thus need a session id to be stored in the browser, I have the following:

```rust
        let (pkce_code_challenge, pkce_code_verifier) = PkceCodeChallenge::new_random_sha256();

        let (auth_url, _csrf_token) = client
            .authorize_url(CsrfToken::new_random)
            .set_pkce_challenge(pkce_code_challenge)
            .add_scope(Scope::new(scope.to_string()))
            .url();

        let mut session = Session::new();
        session.insert(VERIFIER_KEY, pkce_code_verifier).unwrap();

        // the key value for where the session is located in the store
        let cookie = store.store_session(session).await.unwrap().unwrap();
        let cookie = format!("{}={}; SameSite=Lax; Path=/", SESSION_COOKIE, cookie);
        tracing::debug!("\n 🔑 cookie: {:?}", cookie);

        // Store the session key into the browser cookie header
        let mut headers = HeaderMap::new();
        headers.insert(SET_COOKIE, cookie.parse().unwrap());
        tracing::debug!("\n 📖 headers: {:?}", headers);

        // Redirect to auth service
        let uri: Uri = auth_url.to_string().parse().unwrap();
        tracing::debug!("\n🟢{} endpoint redirect: {}", auth_source, uri);
        (headers, Redirect::to(uri))
```

However, when I pull the store for the shared state, and lookup the session using the browser's session cookie...
```rust
        tracing::debug!("\n👉 ...received a code:\n{:?}\n", &auth_req.code);

        tracing::debug!("\n📚store:\n{:?}\n", &store);
        // retrieve the session by first getting the id from the cookies
        let session_id = cookies.get(SESSION_COOKIE).unwrap();
        tracing::debug!("\n 1️⃣  {} cookie:\n{:?}\n", &SESSION_COOKIE, &session_id);

        let session = store.load_session(session_id.to_string()).await.unwrap();
        tracing::debug!("\n 2️⃣ session:\n{:?}\n", &session);

        let pkce_verifier: PkceCodeVerifier = session.unwrap().get(VERIFIER_KEY).unwrap();
        tracing::debug!("\n 3️⃣ verifier:\n{:?}\n", pkce_verifier.secret());

        // Get an auth token
        let token_response = client
            .exchange_code(AuthorizationCode::new(auth_req.code.clone()))
            .set_pkce_verifier(pkce_verifier)
            .request_async(async_http_client)
            .await
            .unwrap();

        tracing::debug!(
            "\n✅ Auth provider returned the following token (opaque):\n{:?}\n",
            token_response
        );

```

... the session does not always return a `Some` value.  I'm at a loss to figure out why this might be.  My suspicion is that it has to do with making sure I clear the cookies once I can to ensure I can proceed with repeating the process with another authentication provider.  Right now, it's perfectly idempotent for a single provider, but not when I switch.  

Note: I'm testing out about 6 different clients, each for a different authenticating service.  I'll be sure to share the example once it's up and running.  I also hope to have it be sufficiently robust/generic for broader open source use.

**Comment by EdmundsEcho** [comment]
The issue turned out to be inconsistent use of `localhost` vs a test domain I was using (same dns, but different domain).  So, the cookies were being stored in different namespaces.

I also ended up using Redis to maintain the state between the two calls to the authenticating service.

This was a solid and productive experience.

Thank you!!
