### ISSUE TITLE
Document that omitting the client secret requires also changing the client's auth type

### ISSUE THREAD

**Issue by bstrie** [ramosbugs/oauth2-rs#176]
I've had a heck of a time trying to figure out why my requests were failing to authorize with my oauth provider unless a client secret was set (which is the case in the basic example in the documentation). Turns out, the problem was that I needed to switch my client's auth type from BasicAuth to RequestBody, which I only figured out after a lot of searching, scratching my head, and staring at this crate's source code. I'd be happy to add a line documenting this fact somewhere, if you can point me to where you'd like it to live.

**Comment by ramosbugs** [comment]
Hey @bstrie, thanks for filing this issue! I think this is actually a bug and not just a documentation deficiency. Based on [Section 2.3.1](https://datatracker.ietf.org/doc/html/rfc6749#section-2.3.1) of RFC 6749, it doesn't seem like there's any valid use case for using the HTTP `Authorization` (with `Basic`) header in the absence of a client secret. So, I'm going to change the library's behavior to always include the client ID in the request body when there is no secret.
