### ISSUE TITLE
DeviceAccessTokenRequest compile error if we use request_async

### ISSUE THREAD

**Issue by LorenzoLeonardo** [ramosbugs/oauth2-rs#187]
Hello

I found a problem with DeviceAccessTokenRequest when using it as async. There is an async implementation found on your codes but there is a compile error when using it. I found a sample but it is a sync example https://docs.rs/oauth2/latest/oauth2/#device-code-flow. I am creating an async implementation of it.

    pub async fn get_token(&mut self) -> Result<UserToken, Box<dyn std::error::Error>> 
    {
        let request_token =
            self.client.as_ref().unwrap()
            .exchange_device_access_token(&self.devicecode_result.as_ref().unwrap());
            
        let token_result = request_token.request_async(async_http_client, std::thread::sleep, None).await?;

        println!("Access Token: {}", token_result.clone().access_token().secret().to_string());
        Ok(UserToken{token: token_result.clone().access_token().secret().to_string()})
    }

Compile Errors:
.request_async(async_http_client, std::thread::sleep, None).await?;
     |              ^^^^^^^^^^^^^ `()` is not a future

2363 |         SF: Future<Output = ()>,
     |             ^^^^^^^^^^^^^^^^^^^ required by this bound in `DeviceAccessTokenRequest::<'a, 'b, TR, TT, EF>::request_async`

**Comment by LorenzoLeonardo** [comment]
By the way this request_async method is found at line 2353 of https://github.com/ramosbugs/oauth2-rs/blob/main/src/lib.rs. There is a compile error related to SF: Future<Output = ()>

**Comment by LorenzoLeonardo** [comment]
It is ok now, instead of using std::thread::sleep, I will use the tokio::time::sleep for async implementations. Please close this thread.

**Comment by CosminPerRam** [comment]
I too have encountered this problem yesterday, a note on docs saying to use `tokio::time::sleep` would be nice.

**Comment by ramosbugs** [comment]
I'd be happy to merge a PR that improves the documentation around this!

**Comment by LorenzoLeonardo** [comment]
@ramosbugs  thank you very much. Let me know if I can add some examples using this.

**Comment by LorenzoLeonardo** [comment]
Hello DavidLet me know how I can help to add examples using async.Sent from my Galaxy
-------- Original message --------From: David Ramos ***@***.***> Date: 10/7/22  14:30  (GMT+08:00) To: ramosbugs/oauth2-rs ***@***.***> Cc: Lorenzo Leonardo ***@***.***>, Author ***@***.***> Subject: Re: [ramosbugs/oauth2-rs] DeviceAccessTokenRequest compile error if we use request_async (Issue #187) 
I'd be happy to merge a PR that improves the documentation around this!

**Comment by LorenzoLeonardo** [comment]
Closing this issue
