### ISSUE TITLE
"Device code expired" vs token_expired from endpoint timing issue

### ISSUE THREAD

**Issue by LorenzoLeonardo** [ramosbugs/oauth2-rs#193]
Hello David

I found some timing issue behavior for not logging in in the cloud during request_async() of exchange_device_access_token() after 15 mins(Microsoft endpoint).

This line sometimes return ->  line 2375 break Err(RequestTokenError::Other("Device code expired".to_string()));

But sometimes the endpoint returns "{\"error\":\"expired_token\",\"error_description\":\"AADSTS70020: The provided value for the input parameter 'device_code' is not valid. This device code has expired.\\r\\n

Would it be better to change this String from "Device code expired" to "expired_token"? Or make it into RequestTokenError::ServerResponse("expired_token")? To have uniformity of error handling? I guess they have the same meaning but there is just a timing when it errors from the endpoint and error at line 2375

**Comment by LorenzoLeonardo** [comment]
Hello David

I have a PR for this. Please check and review.

**Comment by LorenzoLeonardo** [comment]
Thanks for merging this change David, by the way, do you have plans for when to upgrade the version number of this crate? Thanks a lot.

**Comment by ramosbugs** [comment]
I just published version 4.3.0, which includes this fix.

**Comment by LorenzoLeonardo** [comment]
nice, thank you very much.
