### ISSUE TITLE
How to inspect headers/error message on a failed refresh?

### ISSUE THREAD

**Issue by thomasmost** [ramosbugs/oauth2-rs#198]
I am getting a RefreshExchangeFailed error on one of my connections when trying to get a new access token. How can I inspect the headers (or otherwise view the full response)?

**Comment by LorenzoLeonardo** [comment]
You can create a custom Http clients. Just follow the signature instructed in this document under custom https://docs.rs/oauth2/latest/oauth2/.

By the way, set this in your toml file if you wanted to make a custom http client -> oauth2 = { version = "...", default-features = false }

**Comment by ramosbugs** [comment]
Thanks, @LorenzoLeonardo.

Additionally, I'd suggest:
1) Walking and printing the [`source`](https://doc.rust-lang.org/nightly/core/error/trait.Error.html#method.source) chain on the `RequestTokenError`, which reveals the underlying errors that caused each higher-level error. This will often identify common issues like deserialization errors and is generally a useful practice for handling errors in Rust.
2) Depending on which HTTP client you're using, you may have some success enabling debug/trace logging levels (e.g., if using `log4rs`).

**Comment by LorenzoLeonardo** [comment]
I added a sample custom HTTP client using curl.
Please check my repo @thomasmost  https://github.com/LorenzoLeonardo/oauth2-rs-examples

**Comment by thomasmost** [comment]
Thanks for the help! I really appreciate it

@ramosbugs Walking the error doesn't show me the headers themselves, and doesn't seem to get too granular as to what the real problem is. I really need to pull the third party request_id off the headers to debug... 

Turning to @LorenzoLeonardo's solution—thank you so much for attaching this example! I added the following:

```rust
    // to print human readable response
    let s = match std::str::from_utf8(&data) {
      Ok(v) => v,
      Err(e) => panic!("Invalid UTF-8 sequence: {}", e),
  };
    eprintln!("Readable headers/body: {}", s);
```

...since before it was printing out the raw utf-8 sequence... and then added this at the beginning:

```
// to include headers in response printout
easy.show_header(true);
```

...but this causes the token_exchange to fail with the following error trace:
```
Failed to parse server response
expected value at line 1 column 1
```

I assume this is because `show_headers` prepends the headers to the json response body the `oauth2` lib expects... but then how do I pull the headers off the response otherwise?

Thanks again!

**Comment by thomasmost** [comment]
Solution: Have to add a `header_function` callback to the transfer object

```rust

        transfer.header_function(|header| {
            print!("header: {}", std::str::from_utf8(header).unwrap());
            true
        }).unwrap();
```
