### ISSUE TITLE
Token Revocation Device Code Work-Flow - Access token is empty reply

### ISSUE THREAD

**Issue by LorenzoLeonardo** [ramosbugs/oauth2-rs#199]
Hello

I got this parse error response when using 
let token_to_revoke = match Some(refresh_token) {
    Some(token) => token.into(),
    None => (&access_token).into(),
};
client = client.set_revocation_uri(
                    RevocationUrl::new(self.oauth2_endpoint.revocation_endpoint.clone()).unwrap(),
                )
                client
                    .revoke_token(token_to_revoke)
                    .expect("This must have the right token")
                    .request_async ...

I am not sure if I have some lacking steps in setting up sa client. Please let me know what I am missing.

Request:
Request: URL=Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("graph.microsoft.com")), port: None, path: "/beta/me/invalidateAllRefreshTokens", query: None, fragment: None }
Request: Header={"accept": "application/json", "content-type": "application/x-www-form-urlencoded"}
Request: Method=POST
Request: Body="token=M.R3_BL2.-Cd*Sr1A*hpVWufEK2FqWxHUAYved1A1yZu7o74VLPI9*SxUVuf1pzn0roqgCOP6GLJaSULYpsVitIIwx6QeBxtOL*Oados1q7LxLrvdx6Z%21DnUyfrqeBSGdGvc4E4c6YfHOw8hVQHJYwpG240j74YLoi%21srUJWIqxDFwbVkCYC43rkFu4V2BwWg*3MFdr7dGQYEaoNejGMIxsEQ2Nk%21T*65wnxpoHfKyUNNqx4oTNssU*hosJKn5F9dhQ5RkG2fHyezOZGycPfSnIO2zJwNAISFRQNgNlqQIspF2Z4ytnS6urTfy7I9yvRn*GtSJPw%24%24&token_type_hint=refresh_token&client_id=CLIENT_ID"

Response:
{\"error\":{\"code\":\"InvalidAuthenticationToken\",\"message\":\"Access token is empty.\",\"innerError\":{\"date\":\"2022-11-24T07:25:58\",\"request-id\":\"51403c6c-617a-4277-b1e1-06ba56269218\",\"client-request-id\":\"51403c6c-617a-4277-b1e1-06ba56269218\"}}}

**Comment by ramosbugs** [comment]
I don't see anything on the Microsoft [docs](https://learn.microsoft.com/en-us/graph/api/user-invalidateallrefreshtokens?view=graph-rest-beta&tabs=http) that suggest this endpoint is designed to implement RFC 7009, which is what this crate's token revocation is designed to interface with. This may just be a proprietary API that needs to be accessed outside of this crate.

**Comment by LorenzoLeonardo** [comment]
Closing this issue. Already find another way.
