### ISSUE TITLE
Cancelling the loop while polling for access token

### ISSUE THREAD

**Issue by LorenzoLeonardo** [ramosbugs/oauth2-rs#201]
Hello David

Is there a way to cancel this loop while polling for access token?

        // Loop while requesting a token.
        loop {
            let now = (*self.time_fn)();
            if now > timeout_dt {
                break Err(RequestTokenError::ServerResponse(
                    DeviceCodeErrorResponse::new(
                        DeviceCodeErrorResponseType::ExpiredToken,
                        Some(String::from("This device code has expired.")),
                        None,
                    ),
                ));
            }

            match self.process_response(http_client(self.prepare_request()?), interval) {
                DeviceAccessTokenPollResult::ContinueWithNewPollInterval(new_interval) => {
                    interval = new_interval
                }
                DeviceAccessTokenPollResult::Done(res, _) => break res,
            }

            // Sleep here using the provided sleep function.
            sleep_fn(interval);
        }

The usecase is what if the user application wanted to cancel during this period.

**Comment by ramosbugs** [comment]
hmm... I think the simplest option is probably to use `request_async` instead of the sync version, and then you can simply drop the future. Would that work?

**Comment by LorenzoLeonardo** [comment]
hmm I am not sure about that, how about adding a cancel flag, and there is a new function that changes the flag if there is a cancel request? And if it is canceled we return an Err like a sort of DeviceCodeErrorResponseType::Canceled?

**Comment by LorenzoLeonardo** [comment]
Hello David

I am showing you an idea in a PR to cancel the polling of access token.
https://github.com/ramosbugs/oauth2-rs/pull/202

Let me know if this cause issues.

**Comment by LorenzoLeonardo** [comment]
Or, how about adding this logic to this line, if we add like a Cancel Error return from the http callback and process it here.
This will end the loop since it will be Done with DeviceCodeErrorResponseType::CancelledPolling error return to the user.

    fn process_response<RE>(
        &self,
        res: Result<HttpResponse, RE>,
        current_interval: Duration,
    ) -> DeviceAccessTokenPollResult<TR, RE, DeviceCodeErrorResponse, TT>
    where
        RE: Error + 'static,
    {
        let http_response = match res {
            Ok(inner) => inner,
            Err(error) => {
                if Cancel Err is returned from the http_cliente_callback function then  
                 {
                           return  DeviceAccessTokenPollResult::Done(Err(RequestTokenError::ServerResponse(
                    DeviceCodeErrorResponse::new(
                        DeviceCodeErrorResponseType::CancelledPolling,
                        Some(String::from("Request for access token was cancelled by the user")),
                        None,
                    ),
                )), _)
                }
                // Try and double the current interval. If that fails, just use the current one.
                let new_interval = current_interval.checked_mul(2).unwrap_or(current_interval);
                return DeviceAccessTokenPollResult::ContinueWithNewPollInterval(new_interval);
            }
        };

**Comment by LorenzoLeonardo** [comment]
Hello David 


I have another idea on how to cancel polling for an access token.
https://github.com/ramosbugs/oauth2-rs/pull/203. Let me know if we can improve this.

**Comment by LorenzoLeonardo** [comment]
Closing this issue, I can just Drop the future. Thanks
