### ISSUE TITLE
User-customizable scope separators (feature request)

### ISSUE THREAD

**Issue by dbaynard** [ramosbugs/oauth2-rs#204]
#17 implemented exclusively space-separated scopes, yet some implementations require other separators — a comma, in the example I use.

https://github.com/ramosbugs/oauth2-rs/blob/6a8c89ff11e003975437cd6deb7786d345c1bd7b/src/lib.rs#L1135

It looks like this value would have to be configurable. Would you allow such configuration?

(Happy to PR if needed).

Edit: I know that [RFC 6749: The OAuth 2.0 Authorization Framework](https://www.rfc-editor.org/rfc/rfc6749#section-3.3) only allows for space-separated scopes… unfortunately that is not implemented, in every case.

**Comment by ramosbugs** [comment]
Right, this crate follows the published and widely-adopted standards, which unfortunately means not being able to interoperate with services that implement their own protocols. You'll either need to construct the authorization request URL without using this crate or parse the one returned by this crate and rewrite it to suite your needs (or get the offending service to follow the spec).

**Comment by dbaynard** [comment]
Thanks, I ended up using `add_extra_param` to add a `scope` parameter.

**Comment by dbaynard** [comment]
The same jokers have stashed their token response in nested json (under the `body` top level object key). I presume the 'published and widely-adopted standards' approach means something that violates section 5.1's 'The parameters are serialized into a JavaScript Object Notation (JSON) structure by adding each parameter at the highest structure level.' won't be supported either.

You'd suggest a custom client, here, if I'm to use this crate?

**Comment by ramosbugs** [comment]
> Thanks, I ended up using `add_extra_param` to add a `scope` parameter.

Great idea, that's a better solution.

> You'd suggest a custom client, here, if I'm to use this crate?

Yeah... I think that would give you the most control in processing the request/response payloads and headers
