### ISSUE TITLE
Comments in examples mention csrf_state which does not exist in the code

### ISSUE THREAD

**Issue by taladar** [ramosbugs/oauth2-rs#208]
https://docs.rs/oauth2/4.3.0/oauth2/index.html#example-synchronous-blocking-api

```
// Once the user has been redirected to the redirect URL, you'll have access to the
// authorization code. For security reasons, your code should verify that the `state`
// parameter returned by the server matches `csrf_state`.
```

Presumably this is meant to refer to csrf_token which is set in the code above that comment?

The same issue occurs several times in later examples.

**Comment by ramosbugs** [comment]
Yup, nice catch. The variable is named `csrf_state` in some of the [other examples](https://github.com/ramosbugs/oauth2-rs/blob/00fa30b336a8b3c9c4c900ae3ccba371459c0ac8/examples/google.rs#L64), but this comment must have become stale at some point.
