### ISSUE TITLE
Better error messages for failed requests

### ISSUE THREAD

**Issue by ilmari-h** [ramosbugs/oauth2-rs#210]
Is it currently possible to get some kind of debug logging for failed requests? It seems errors are mapped to hard coded strings like `"Server returned error response"`. 
It would make debugging easier if the actual response sent by the auth server could be accessed or displayed somehow.

**Comment by ramosbugs** [comment]
yup, this crate follows the standard Rust error chaining approach using the `Error` trait's [`source`](https://doc.rust-lang.org/nightly/core/error/trait.Error.html#method.source) method. walking the source chain will reveal the detailed underlying causes of errors.

**Comment by LorenzoLeonardo** [comment]
You can make your own convert @ramosbugs  errors to your custom error.

impl<O, S> From<RequestTokenError<O, StandardErrorResponse<S>>> for YourCustomErrorCodes
where
    O: Error + 'static,
    S: ErrorResponseType + 'static + Display,
{
    fn from(e: RequestTokenError<O, StandardErrorResponse<S>>) -> Self {
        match e {
            ServerResponse(err_server_resp) => {
                ErrorCodes::from_str(&err_server_resp.error().to_string()).unwrap_or_default()
            }
            Request(_) => ErrorCodes::RequestError,
            Parse(_, _) => ErrorCodes::ParseError,
            Other(_) => ErrorCodes::OtherError,
        }
    }
}

impl<RE, T> From<RequestTokenError<RE, T>> for YourCustomError
where
    RE: Error + 'static,
    T: ErrorResponse + 'static,
    YourCustomErrorCodes: From<RequestTokenError<RE, T>>,
{
    fn from(error: RequestTokenError<RE, T>) -> Self {
        log::error!("{:?}", error);
        OAuth2Error::new(YourCustomErrorCodes::from(error))
    }
}

**Comment by ilmari-h** [comment]
Thank you both for the help, seems it was just my lack of knowledge :)
