### ISSUE TITLE
microsoft_devicecode flow broken

### ISSUE THREAD

**Issue by randomairborne** [ramosbugs/oauth2-rs#219]
When attempting to run the microsoft_devicecode example with my azure AD tenant, I get 
```Error: ServerResponse(StandardErrorResponse { error: invalid_scope, error_description: Some("AADSTS70011: The provided value for the input parameter 'scope' is not valid. The scope 'read' does not exist.\r\nTrace ID: 7172ec82-5230-49ab-b98c-a224c8e50500\r\nCorrelation ID: afde4e78-9981-460a-a670-e3ef2679d6dd\r\nTimestamp: 2023-06-14 23:12:54Z"), error_uri: None })```
and when switching it to `XboxLive.signin`, after `exchange_device_access_token` i get `Error: Other("Server returned empty error response")`.

**Comment by ramosbugs** [comment]
@LorenzoLeonardo Do you happen to remember if there's anything that needs to be configured on the Azure side in order for the example to work? Sounds like there might be some missing documentation, but I'm not familiar enough with Azure to know what steps are needed.

**Comment by randomairborne** [comment]
Note: I also switched from `common` to `consumers` to match my tenant type

**Comment by ramosbugs** [comment]
> Note: I also switched from `common` to `consumers` to match my tenant type

ah, that's probably why. Is this the same as Azure AD B2C? See https://learn.microsoft.com/en-us/azure/active-directory-b2c/access-tokens#scopes.

**Comment by randomairborne** [comment]
switching it back didn't seem to fix anything, though?

**Comment by randomairborne** [comment]
I will end up getting a device code and the link i need, but then it will immediately return `Error: Other("Server returned empty error response")` with no further details

**Comment by ramosbugs** [comment]
This error means the server returned 200 OK but no response body, so I'm not sure what additional debug information this crate could provide in that situation. There might be some informative response headers, which you could access by providing a custom `http_client` function to `.request_async()` that wraps whichever HTTP client you're using and looks at the response before passing it back to the crate.

In any case, this isn't an Azure support forum, and it sounds like you're trying to use the example on a different type of tenant than the example was written for. Feel free to contribute a working B2C example if you get it working, but the exact input parameters needed to do that are specific to each provider and not something this crate aims to implement for every possible provider configuration.

**Comment by LorenzoLeonardo** [comment]
> @LorenzoLeonardo Do you happen to remember if there's anything that needs to be configured on the Azure side in order for the example to work? Sounds like there might be some missing documentation, but I'm not familiar enough with Azure to know what steps are needed.

I have a sample working tool using device code flow for microsoft azure than can be able to send email using SMTP XOAUTH2.

The use can configure their Azure portal in what scopes they need to use.

Working program using this library:
https://github.com/LorenzoLeonardo/microsoft-smtp-xoauth2-test-tool

**Comment by LorenzoLeonardo** [comment]
@ramosbugs  This reference is useful. https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-device-code.

For Common/personal user they can use "common" https://login.microsoftonline.com/common/oauth2/v2.0/devicecode & https://login.microsoftonline.com/common/v2.0/oauth2/token.

But for enterprise account with tenant id, they must user this https://login.microsoftonline.com/{tenant or application id}/oauth2/v2.0/devicecode, [https://login.microsoftonline.com/{tenant or application id}/oauth2/v2.0/devicecode](https://login.microsoftonline.com/{tenant or application id}/v2.0/oauth2/token)

**Comment by LorenzoLeonardo** [comment]
@ramosbugs  I made a PR to avoid this confusion, since for Microsoft endpoint there are common user and tenant user.
https://github.com/ramosbugs/oauth2-rs/pull/222
