### ISSUE TITLE
Facebook scopes are None

### ISSUE THREAD

**Issue by Xenfo** [ramosbugs/oauth2-rs#226]
I have the scope set to `public_profile` but when I access `token.scopes()` it returns None.

**Comment by ramosbugs** [comment]
The scopes passed in the request are simply the requested scopes. The authorization server can decide whether or not to grant those scopes, as returned in the token response. Questions about why Facebook does or doesn't grant the requested scopes should be directed to Facebook.

**Comment by Xenfo** [comment]
Thanks for the quick response, as seen below, I've approved scopes so there should be some scopes returned. Is there any way to view the raw request before it's processed into `StandardTokenResponse`?

![image](https://github.com/ramosbugs/oauth2-rs/assets/46873232/56eed435-607d-491e-b844-9fd4b970e3c8)

**Comment by ramosbugs** [comment]
You can access the raw request/response by passing a custom `http_client` function to `request`/`request_async`

**Comment by Xenfo** [comment]
Found the issue, Facebook requires a separate API call to their `https://graph.facebook.com/debug_token` endpoint to get scopes.
