### ISSUE TITLE
Error:  Failed to parse server response. On attempt to exchange token

### ISSUE THREAD

**Issue by ugochukwu-850** [ramosbugs/oauth2-rs#228]
When I try to exchange the code for an access_token, it resolves to an Err , 
```sh
Error:  Failed to parse server response
```

**Comment by ramosbugs** [comment]
This crate follows the standard Rust error chaining approach using the Error trait's [source](https://doc.rust-lang.org/nightly/core/error/trait.Error.html#method.source) method. Walking the source chain will reveal the detailed underlying causes of errors.

**Comment by ramosbugs** [comment]
Here's an example: https://github.com/ramosbugs/openidconnect-rs/blob/414eb35419f84ab370c0d9acc3af72d72b67462c/examples/google.rs#L38-L47

**Comment by ugochukwu-850** [comment]
Thank you
