### ISSUE TITLE
serde compilation error

### ISSUE THREAD

**Issue by jaredallard** [ramosbugs/oauth2-rs#229]
**Version**: `4.4.1`
**rustc --version**: `rustc 1.71.1 (eb26296b5 2023-08-03)`
**cargo --version**: `cargo 1.71.1 (7f1d04c00 2023-07-29)`

Hi! This crate is imported through another package I'm using. When attempting to compile my project, I'm getting the following:

```bash
$ cargo run
... snip ...
   Compiling oauth2 v4.4.1
error[E0507]: cannot move out of `*self` which is behind a shared reference
  --> /Users/jaredallard/.asdf/installs/rust/1.71.1/registry/src/index.crates.io-6f17d22bba15001f/oauth2-4.4.1/src/revocation.rs:57:37
   |
57 | #[derive(Clone, Debug, Deserialize, Serialize)]
   |                                     ^^^^^^^^^
   |                                     |
   |                                     data moved here
   |                                     move occurs because `unrecognized` has type `StandardRevocableToken`, which does not implement the `Copy` trait
   |
   = note: this error originates in the derive macro `Serialize` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider borrowing here
   |
57 | #[derive(Clone, Debug, Deserialize, &Serialize)]
   |                                     +

For more information about this error, try `rustc --explain E0507`.
error: could not compile `oauth2` (lib) due to previous error
```

I'm not the most proficient with Rust (I'm still learning!) so it's possible this might be something wrong with my project. Please let me know if there is anything else I can include in my report or that I can do. Thank you!

**Comment by jaredallard** [comment]
Seemed to be an issue with the version of `serde_json` in use. I was able to fix that by changing the versions. Sorry for the noise!

**Comment by ramosbugs** [comment]
Looks like this was due to serde-rs/serde#2591, which was specific to serde 1.0.184 and not related to this crate's Cargo.toml dependencies.
