### ISSUE TITLE
Should Authorization Code Grant with PKCE require client secret?

### ISSUE THREAD

**Issue by mawkler** [ramosbugs/oauth2-rs#233]
Why does [the example for Authorization Code Grant with PKCE](https://docs.rs/oauth2/latest/oauth2/index.html#getting-started-authorization-code-grant-w-pkce) require a client secret? You specifically state:

> recommended whenever the OAuth2 client has no client secret or has a client secret that cannot remain confidential

Which is my understanding of PKCE as well. This is the line from the example that I'm referring to:

```rust
let client =
    BasicClient::new(
        ClientId::new("client_id".to_string()),
        Some(ClientSecret::new("client_secret".to_string())), // <--- IS THIS CLIENT SECRET REQUIRED?
        AuthUrl::new("http://authorize".to_string())?,
        Some(TokenUrl::new("http://token".to_string())?)
    )
    // Set the URL the user will be redirected to after the authorization process.
    .set_redirect_uri(RedirectUrl::new("http://redirect".to_string())?);
```

I'm relatively new to OAuth, so I apologize if this is a dumb question.

**Comment by ramosbugs** [comment]
Hey @mawkler,

PKCE is optional but [recommended](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-security-topics#section-2.1.1) even for confidential clients (those with a client secret):
> For confidential clients, the use of PKCE [[RFC7636](https://www.rfc-editor.org/info/rfc7636)] is RECOMMENDED, as it provides a strong protection against misuse and injection of authorization codes as described in [Section 4.5.3.1](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-security-topics#pkce_as_injection_protection) and, as a side-effect, prevents CSRF even in presence of strong attackers as described in [Section 4.7.1](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-security-topics#csrf_countermeasures).

**Comment by mawkler** [comment]
@ramosbugs Hmm ok. I'm trying to use the [Authorization Code Flow with (PKCE)](https://auth0.com/docs/get-started/authentication-and-authorization-flow/authorization-code-flow-with-proof-key-for-code-exchange-pkce) because I don't want to store a client secret in the binary for a CLI application I'm building. Is it possible oauth2-rs for this?

**Comment by ramosbugs** [comment]
yes, as indicated in the [docs](https://docs.rs/oauth2/latest/oauth2/struct.Client.html#arguments), anywhere the client secret is an `Option`, it's optional and should be `None` for public clients.

**Comment by mawkler** [comment]
@ramosbugs Ah that makes sense! Thank you!
