### ISSUE TITLE
Does this crate support getting scope data like (profile) ?

### ISSUE THREAD

**Issue by HosMercury** [ramosbugs/oauth2-rs#241]
I saw the Google example 

just get the access_token

and I have successfully implemented that.

but is there a further step to get the scope ( like profile data )?

**Comment by ramosbugs** [comment]
I think you're probably looking for the [openidconnect](https://github.com/ramosbugs/openidconnect-rs) crate.

**Comment by HosMercury** [comment]
it’s a backend and i already reached the point of getting access token by this crate, but what scope should i use and what link should i call finally to get email, username & name of the user
