### ISSUE TITLE
Code review of FusionAuth OAuth2 Rust guide please?

### ISSUE THREAD

**Issue by RichardJECooke** [ramosbugs/oauth2-rs#242]
Hi, I'm writing a quickstart guide on using your library with FusionAuth.

Everything runs, but I think the two Rust files could be improved. I'm not a Rust programmer and I used ChatGPT mostly. Please would you take a look and let me know what to change?

Specifically in the `auth.rs` file:
- Can I get user email by using the oauth lib, instead of a separate call with a separate library (reqwest)?
- Why do I have to `unwrap().unwrap()` the pkce value? If I do it only once the code fails.
- How can I get `await?` to work instead of `match`? The compiler errors with type problems I don't know how to fix.

To run:
```
git clone https://github.com/ritza-co/fusionauth-quickstart-rust-actix-web.git
git checkout code_review
docker compose up 
cd your-application
cargo run
```

You can login with `admin@example.com` and `password` at http://localhost:9012 (and FusionAuth at http://localhost:9011)

**Comment by ramosbugs** [comment]
I would be happy to discuss a consulting arrangement to help your business with this FusionAuth integration. Please email me at ramos@cs.stanford.edu if you'd like to discuss further.
