### ISSUE TITLE
version 4.4.2 doesn't work with Google provided token server

### ISSUE THREAD

**Issue by wt** [ramosbugs/oauth2-rs#259]
The 4.4.2 doesn't work with the token server in my credential config from google (namely "https://oauth2.googleapis.com/token"). The main branch version does. Might be worthwhile to either backport that fix to 4.4.2 or document it somewhere where someone might find it.

**Comment by ramosbugs** [comment]
What error are you seeing? There shouldn't be any recent changes that impact whether the examples work.
