### ISSUE TITLE
Reason of using Fn() instead of FnOnce for AsyncHttpClient and SyncHttpClient

### ISSUE THREAD

**Issue by LorenzoLeonardo** [ramosbugs/oauth2-rs#264]
Hello

I've got a problem regarding this. Previously I was using FnOnce for custom HttpCLient but right now I already got this error due to Fn() change. This is a problem if the callback function is a closure.

> cannot move out of `inter`, a captured variable in an `Fn` closure
> `inter` is moved hererustc[Click for full compiler diagnostic](rust-analyzer-diagnostics-view:/diagnostic%20message%20%5B0%5D?0#file%3A%2F%2F%2Fe%253A%2FVS_Codes%2Fmodern-auth-> service%2Fsrc%2Foauth2%2Fdevice_code_flow.rs)
> device_code_flow.rs(395, 9): captured outer variable
> device_code_flow.rs(397, 52): captured by this `Fn` closure
> device_code_flow.rs(398, 13): variable moved due to use in coroutine
> device_code_flow.rs(398, 13): move occurs because `inter` has type `I`, which does not implement the `Copy` trait

**Comment by ramosbugs** [comment]
closures can be `Fn()` if you don't move values into them. they have to be callable multiple times

**Comment by LorenzoLeonardo** [comment]
> closures can be `Fn()` if you don't move values into them. they have to be callable multiple times

This is the problem, I have variables move into them.

**Comment by LorenzoLeonardo** [comment]
![image](https://github.com/ramosbugs/oauth2-rs/assets/97872577/14b79cc3-5a4c-4f06-80de-b6e3e77e200e)

**Comment by LorenzoLeonardo** [comment]
![image](https://github.com/ramosbugs/oauth2-rs/assets/97872577/87064541-e84f-4404-b1dc-b665f2ea75a1)

**Comment by ramosbugs** [comment]
this can be solved by some combination of:
- passing references instead of ownership
- cloning (or cloning an `Arc` for a less expensive alternative)
- using `async` instead of `async move`

**Comment by LorenzoLeonardo** [comment]
> this can be solved by some combination of:
> 
> * passing references instead of ownership
> * cloning (or cloning an `Arc` for a less expensive alternative)
> * using `async` instead of `async move`

It seems, it will be simplier if FnOnce is used just like in the previous implementation especially I am dealing with tokio::spawn() for polling of access token routine. If FnOnce is used I will just simply clone the callback. If there is a way that the API could support both FnOnce and Fn will be good.

**Comment by ramosbugs** [comment]
`Fn()` is needed because of the device authorization flow, which repeatedly uses the HTTP client to poll the device authorization endpoint. It's not worth the complexity of having two different `AsyncHttpClient` traits for single-use and multi-use HTTP clients. Many APIs in Rust require `Fn()`. I don't think it's a problem.

> The problem is when you are dealing with tokio::spawn, you are forced to use async move

That's fine, then wrap the things you need in an `Arc` and clone those as needed, or manually build a struct that implements the `AsyncHttpClient` trait instead of using a closure.
