### ISSUE TITLE
DPoP support

### ISSUE THREAD

**Issue by Gbr22** [ramosbugs/oauth2-rs#265]
Does this crate implement [OAuth 2.0 Demonstrating Proof of Possession (DPoP)](https://datatracker.ietf.org/doc/html/rfc9449)?
If not, do you plan on implementing it?

**Comment by ramosbugs** [comment]
Not currently. See discussion in https://github.com/ramosbugs/openidconnect-rs/issues/54 and https://github.com/ramosbugs/openidconnect-rs/pull/109. Given the complexity, I think this would make sense as a separate crate built on top of this one, similar to other JWT functionality (#211).
