### ISSUE TITLE
`StandardTokenResponse` does not support twitch oauth response

### ISSUE THREAD

**Issue by SarthakSingh31** [ramosbugs/oauth2-rs#269]
From [dev.twitch.tv](https://dev.twitch.tv/docs/authentication/getting-tokens-oauth/#authorization-code-grant-flow).
```json
{
  "access_token": "rfx2uswqe8l4g1mkagrvg5tv0ks3",
  "expires_in": 14124,
  "refresh_token": "5b93chm6hdve3mycz05zfzatkfdenfspp1h1ar2xxdalen01",
  "scope": [
    "channel:moderate",
    "chat:edit",
    "chat:read"
  ],
  "token_type": "bearer"
}
```
The oauth response returns an array of scopes instead of a space delimited string of scopes.
The `StandardTokenResponse` only supports the space delimited string of scopes. It would be very useful if it supported both.
https://github.com/ramosbugs/oauth2-rs/blob/30ced325da24312c4e6b9d802adcb36a88594353/src/token/mod.rs#L611-L616

**Comment by ramosbugs** [comment]
The TL;DR is to implement the `TokenResponse` trait for a custom struct that matches Twitch's response. As the name `StandardTokenResponse` implies, it adheres to the standard. The reason the trait exists separately from the struct is to accommodate these scenarios.

**Comment by paulm17** [comment]
@ramosbugs is it possible for you to create an example?  I'm able to get amazon, facebook, github, google, linkedin, microsoft, reddit, tiktok, twitter to work.  But due to twitch not adhering to the spec.   I'm completely stuck.  

Thanks for your consideration.
