### ISSUE TITLE
RequestTokenError should include the inner error when displayed as string

### ISSUE THREAD

**Issue by reimarstier** [ramosbugs/oauth2-rs#273]
If the format argument for `RequestTokenError` were to include the inner error, the "request failed" error would be more meaningful itself. Others have noticed this as well in #210. For me this was rather suprising that all kinds of errors (certificate invalid, invalid credentials, dns resolution error, no connection/response) are all mapped to the same error when the source error is not included. Apart from that using your library was amazing. I learned a lot about types from your library :-)

So, is this intended behavior or is this something you would consider changing?

## Current implementation

https://github.com/ramosbugs/oauth2-rs/blob/daf4db6a928b81fbb4a58ce1c79085f2f2aeb4aa/src/error.rs#L112-L135

## Source code download differs

I also noticed that the source code downloaded in the [release](https://github.com/ramosbugs/oauth2-rs/archive/refs/tags/4.4.2.tar.gz) does not contain the format string of the `ServerResponse` error. Why is that?

Expected to contain the following error format for ServerResponse:
```rust
     #[error("Server returned error response: {0}")] 
```

But it is not not containing the `{0}` in the format argument:
```rust
///
/// Error encountered while requesting access token.
///
#[derive(Debug, thiserror::Error)]
pub enum RequestTokenError<RE, T>
where
    RE: Error + 'static,
    T: ErrorResponse + 'static,
{
    ///
    /// Error response returned by authorization server. Contains the parsed `ErrorResponse`
    /// returned by the server.
    ///
    #[error("Server returned error response")]
    ServerResponse(T),
    ///
    /// An error occurred while sending the request or receiving the response (e.g., network
    /// connectivity failed).
    ///
    #[error("Request failed")]
    Request(#[source] RE),
    ///
    /// Failed to parse server response. Parse errors may occur while parsing either successful
    /// or error responses.
    ///
    #[error("Failed to parse server response")]
    Parse(
        #[source] serde_path_to_error::Error<serde_json::error::Error>,
        Vec<u8>,
    ),
    ///
    /// Some other type of error occurred (e.g., an unexpected server response).
    ///
    #[error("Other error: {}", _0)]
    Other(String),
}
```

## Changed format string

```rust
    #[error("Request failed: {0}")]
    Request(#[from] RE),
```

**Comment by reimarstier** [comment]
At the moment I did the following to decode the error by myself:

```rust
#[derive(thiserror::Error, Debug)]
pub struct WrappedRequestTokenError(pub RequestTokenError<OidcClientError, BasicErrorResponse>);
impl Display for WrappedRequestTokenError {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", parse_oauth_request_error(&self.0))
    }
}

fn parse_oauth_request_error(error: &RequestTokenError<OidcClientError, BasicErrorResponse>) -> String {
    match error {
        RequestTokenError::ServerResponse(ref server_error) => {
            server_error.error().to_string()
        }
        RequestTokenError::Request(ref request_error) => {
            request_error.to_string()
        }
        RequestTokenError::Parse(ref error_token, ref _error_response) => {
            error_token.to_string()
        }
        RequestTokenError::Other(ref other) => {
            other.to_string()
        }
    }
}
```

**Comment by ramosbugs** [comment]
> I also noticed that the source code downloaded in the [release](https://github.com/ramosbugs/oauth2-rs/archive/refs/tags/4.4.2.tar.gz) does not contain the format string of the `ServerResponse` error. Why is that?

The `main` branch of this repo corresponds to the 5.x release of this crate, which is currently in alpha (safe to use, but not guaranteed API-stable).

**Comment by ramosbugs** [comment]
Note that `RequestTokenError::ServerResponse` is an exception to this rule because its inner error doesn't itself implement the `Error` trait, so it can't be part of the cause chain. That's why it was added to the `Display` output.

**Comment by reimarstier** [comment]
Oh wow, thanks for the elaborate explanations. This is very helpful.
