### ISSUE TITLE
Add support for RFC 9068

### ISSUE THREAD

**Issue by gibbz00** [ramosbugs/oauth2-rs#274]
RFC 9068: JWT Profile for OAuth 2.0 Access Tokens: tools.ietf.org/html/rfc9068

Suppose it would be something similar to: [openidconnect::IdTokenClaims](https://docs.rs/openidconnect/latest/openidconnect/struct.IdTokenClaims.html). I can begin to draft a PR if the addition seems reasonable.

**Comment by gibbz00** [comment]
From only taking a very brief look at how this can be implemented:

There are some [helpers](https://github.com/ramosbugs/openidconnect-rs/blob/main/src/helpers.rs) in the `openidconnect` crate which implement parts of [RFC7519](tools.ietf.org/html/rfc7519). `RFC9098` uses it too. One option would be to create a helper crate which both `oath2` and `openidconnect` depend on. Or one could move `helpers.rs` to `oath2`, for example. Suppose @ramosbugs has the final say in this.

**Comment by gibbz00** [comment]
Sketched a partial implementation downstream for anyone interested in copying it for their own use:

https://github.com/gibbz00/amigo/blob/42a4ee83e8dfdb4df40cfacf7734cea1d31f387a/crates/utils/jwt-access-token/src/token.rs#L7

**Comment by ramosbugs** [comment]
See https://github.com/ramosbugs/openidconnect-rs/issues/160#issuecomment-2063885944

JWT functionality adds significant complexity that I don't want to add as a maintenance burden to this crate. Instead, it can be built as a separate crate on top of this one and maintained separately, similar to my `openidconnect` crate.

**Comment by gibbz00** [comment]
Aight, ok with that 😊
