### ISSUE TITLE
The "state" parameter should be per-request for CSRF protection

### ISSUE THREAD

**Issue by jtgeibel** [ramosbugs/oauth2-rs#28]
I'm working to update the crates.io codebase from 0.3 to 1.0+.  After updating the relevant call sites, I'm running into a borrow error because the `set_state` function is part of the builder pattern for `Config` (and takes self by value).  Previously a per-request state value was provided as a parameter to `authorize_url`.

Here is the relevant code and the diff addressing the API change:

```diff
    let state: String = thread_rng().gen_ascii_chars().take(16).collect();
     req.session()
         .insert("github_oauth_state".to_string(), state.clone());
 
-    let url = req.app().github.authorize_url(state.clone());
+    let url = req.app().github.set_state(&state[..]).authorize_url();
```

Basically, `req.app()` returns a `&Arc<App>` where `App` is a struct initialized at boot and containing a field `github` of type `oauth2::Config`.  This code results in an error "cannot move out of borrowed content".

The old API allowed a per-request state value to be easily supplied to each `authorize_url` call.  As seen in the code above this random state is stored in the session.  It is recovered and checked by the callback endpoint later in the authorization flow.

With the new API the state parameters is captured as part of the builder pattern and it seems this encourages reuse of the same state across multiple requests to the authorization server.  Since the authorization URL (and embedded state parameter) are shared with the user's browser, it is easy for anyone to predict the state if it is reused.  From section [10.2](https://tools.ietf.org/html/rfc6749#section-10.12) of the spec, where "binding value" refers to the state parameter:

> The binding value used for CSRF protection MUST contain a non-guessable value (as described in
Section 10.10), and the user-agent's authenticated state (e.g., session cookie, HTML5 local storage) MUST be kept in a location accessible only to the client and the user-agent (i.e., protected by same-origin policy).

For now, I can work around this with the following, but it seems that the current API doesn't encourage sufficient CSRF protections.

```diff
-    let url = req.app().github.authorize_url(state.clone());
+    let mut url = req.app().github.authorize_url();
+    url.query_pairs_mut().append_pair("state", &state[..]);
```

**Comment by lipanski** [comment]
fair point. bit late to go back to the old interface of `authorize_url`, though that would be my preferred solution. another option would be to clear the `state` attribute within `authorize_url`, but that would be a bit surprising. any other way to keep backwards compatibility of (at least) the `authorize_url` definition?

**Comment by lipanski** [comment]
something like `Config.authorize_url_with_state` (with a state argument) + deprecating `set_state` could also work.

**Comment by jtgeibel** [comment]
> something like `Config.authorize_url_with_state` (with a state argument) + deprecating `set_state` could also work.

This is what I had in mind as well.  I hope to find time soon to put a PR together.

I also see that `Config` is now clone in the 1.3.0 release.  This will clean up the workaround some, as I can clone the config, mutate the state, call `authorize_url`, and then drop the clone.
