### ISSUE TITLE
Support for non-JavaScript WebAssembly

### ISSUE THREAD

**Issue by anderspitman** [ramosbugs/oauth2-rs#291]
I'm implementing a server-side library that I would like to be usable in Go/JavaScript/Rust/Python. I'm investigating whether it would be feasible to use WebAssembly for sharing code between the different language implementations. Part of what the library does is act as an OAuth2 and OIDC client. Currently, oauth2-rs supports reqwest in wasm, but apparently only when using the async http client and compiled with wasm-bindgen. Is that an accurate assessment?

I'm wondering if there's any way to run oauth2-rs in wasm in other languages. I'm guessing with would need to involve WASI or maybe something like [extism](https://github.com/extism/extism), but figured I should check here in case I'm missing something.

**Comment by ramosbugs** [comment]
Hey @anderspitman ,

This level of WASM interoperability is a bit outside my area of expertise. If there are some straightforward changes needed to support other WASM targets (i.e., via feature flags or conditional compilation), I'd be open to PRs, but I won't have the bandwidth to research and implement support for other WASM targets myself.

**Comment by anderspitman** [comment]
Thanks @ramosbugs. I was able to get my code to work by using a custom HTTP client as documented [here](https://docs.rs/oauth2/latest/oauth2/#importing-oauth2-selecting-an-http-client-interface). Thanks for the excellent API design.

So far I haven't even managed to get reqwest to work in wasm so I'm not sure there's any point in trying to make oauth2-rs work seamlessly until I know that works.
