### ISSUE TITLE
reqwest version out of date?

### ISSUE THREAD

**Issue by rogusdev** [ramosbugs/oauth2-rs#292]
The latest release for oauth2 4.4.2 is pinned to reqwest 0.11 (and currently uses 0.11.27 as the last in that minor version) but 0.12 has been out for a long while now. I see that main here has been using 0.12 for 8 months now https://github.com/ramosbugs/oauth2-rs/commit/408ecab500158145bf249e78a73a8010933bb0e2 . But when I attempt to use latest 0.12 with 4.4.2 in my application, I get an error about conflicting versions of reqwest::Error, below

`cargo tree` identified oauth2 as the source of the conflicting version of reqwest.

Is there a suggested workaround, or a new version forthcoming? (For the moment I am keeping my application's version pinned to 0.11.27 as well, but I would like to be able to upgrade.)

Error:
```
note: `reqwest::error::Error` is defined in crate `reqwest`
  --> /home/chris/.cargo/registry/src/index.crates.io-6f17d22bba15001f/reqwest-0.11.27/src/error.rs:16:1
   |
16 | pub struct Error {
   | ^^^^^^^^^^^^^^^^
note: `reqwest::Error` is defined in crate `reqwest`
  --> /home/chris/.cargo/registry/src/index.crates.io-6f17d22bba15001f/reqwest-0.12.9/src/error.rs:16:1
   |
16 | pub struct Error {
   | ^^^^^^^^^^^^^^^^
   = note: perhaps two different versions of crate `reqwest` are being used?
```

Thanks

**Comment by ramosbugs** [comment]
Upgrading `reqwest` from 0.11 to 0.12 is a breaking change to this crate's public API, so only the 5.x major release uses 0.12. I'd suggest using `oauth2 5.0.0-rc.1`.

**Comment by rogusdev** [comment]
Ah, ok, so I will wait until 5.0 is stabilized and stay on 0.11 for now I suppose. Thanks for confirming!
