### ISSUE TITLE
Make BasicClient cloneable

### ISSUE THREAD

**Issue by jongiddy** [ramosbugs/oauth2-rs#42]
`Client` implements `Clone` if the 3 generic types implement `Clone`. `BasicClient` sets the generic types to types that appear to be cloneable but do not implement `Clone`. Hence, `BasicClient` does not implement `Clone`.

Is there a reason for this, or is it just an oversight?

The reason I want to clone a `BasicClient` is that I have decomposes the code for the redirect server into a different location to the rest of the OAuth code, so I want to set the client's `redirect_url` in a different function.

**Comment by ramosbugs** [comment]
Thanks for testing out the alpha and filing this issue! It was just an oversight; should be fixed on the latest master.
