### ISSUE TITLE
Support multiple http backends

### ISSUE THREAD

**Issue by bachp** [ramosbugs/oauth2-rs#49]
The current implemenation is using curl do do HTTP requests. There is a #46 that would change from curl to `reqwest` in order to provide an Async API.

However it would be nice to be able to support different HTTP backends like `actix-web` and `hyper`.

@ramosbugs Proposed to use the `hyper::client::connect::Connect` trait as an interface. This would mean that hyper can easily be used by default. Other libraries would need to provice wrappers that adapt them to the `Connect` trait. This seems like a more viable option than having features for different options.

My specific use case is to use it with the `actix-web` client library in order to do the calls within the context of the actix actor system. Actix web i is used to provie the complete OpenID Connect Workflow.

**Comment by bachp** [comment]
Actix also supports [Sync Actors](https://actix.rs/actix/actix/sync/index.html), so it is not that crucial.

It's probably more an ideal (that is not necessary) to have everything done using actix. But I think a pure rust solution (like `hyper`) that does not depend on curl would be a better default.

**Comment by ramosbugs** [comment]
multiple clients are supported in the latest master
