### ISSUE TITLE
Breaking change for default auth being changed to Basic Auth not clear enough

### ISSUE THREAD

**Issue by dnsco** [ramosbugs/oauth2-rs#58]
First off, let me say thanks for the library!

I have to admit, I only skimmed the changelog, but this one was buried at the very bottom and I did not see it, and was the only breaking change I encountered.

I spent several hours figuring out that that there were different auth schemes, after I'd figured out how to change it it worked.

My process of debugging it was rather roundabout as well.
- This was complicated by the error message's cause showed up as "missing field `error` at line 1 column 100".
- When I used I debugged the error, it showed an array of bytes rather than a string which I then copied and pasted from the terminal and converted to a string to read, there is probably a more efficient way to have done this, but it required too much mucking around in figuring out how this library worked.

**Potential Mitigations** 
- Make a more clear upgrade guide somewhere before 2.0 that has the change in auth scheme marked more clearly
- Store the response_body on RequestTokenError::Parse as a String, rather than a Vec<u8> and change the display to show it. The display is currently "Failed to parse server response" which is really difficult to act off of.

I would be happy to help with these changes if they'd be accepted.

Thanks again for the library!

**Comment by ramosbugs** [comment]
Thanks for the feedback! Apologies that this change caused a hassle for you. An upgrade guide sounds like a great idea. For the latter suggestion, returning the response body as a string makes it hard to deal with responses that fail to decode as valid UTF-8, so I'd prefer to leave it to client applications to decide how to deal with that situation. A string also makes it slightly more likely that client applications will end up logging the malformed response body, which may include sensitive secrets.

I'm traveling for the next two weeks, but I'll take a closer look at this issue when I get back!

**Comment by ramosbugs** [comment]
It looks like the auth schemes change was documented in the changelog for https://github.com/ramosbugs/oauth2-rs/releases/tag/2.0.0-alpha.1, but I still agree that a single upgrade guide would be useful to save people time.
