### ISSUE TITLE
Add option to skip encoding credentials

### ISSUE THREAD

**Issue by s-panferov** [ramosbugs/oauth2-rs#64]
Hello. I'm trying to use the library with Amazon Cognito and I get a `unathorized_client` error because of Cognito [requires](https://docs.aws.amazon.com/cognito/latest/developerguide/token-endpoint.html) just plain base64 encoding of `client_id:client_secret` without any additional urlencode.

**Comment by ramosbugs** [comment]
Unfortunately, the OAuth spec is very clear here:

> Clients in possession of a client password MAY use the HTTP Basic
   authentication scheme as defined in [RFC2617] to authenticate with
   the authorization server.  The client identifier is encoded using the
   "application/x-www-form-urlencoded" encoding algorithm per
   Appendix B, and the encoded value is used as the username; the client
   password is encoded using the same algorithm and used as the
   password.

https://tools.ietf.org/html/rfc6749#section-2.3.1

I would file a bug with Amazon if their product isn't accepting the only valid encoding according to the spec. At this point, I don't think it makes sense to make additional changes to this crate to support non-compliant OAuth providers.
