### ISSUE TITLE
recommended rust implementation of local auth code function?

### ISSUE THREAD

**Issue by hrbigelow** [ramosbugs/oauth2-rs#66]
I would like to use this crate for the code grant flow, but also implement a local "server" for processing the authorize_url, [here](https://github.com/ramosbugs/oauth2-rs/blob/58f07b1e92b0e2d6fc8b80157973aef2bfd54d22/examples/google.rs#L82).

What would be the recommended crate for that?  I've looked at oxide-auth and it looks pretty good, but is there some technique within this crate?

Thanks very much!

**Comment by ramosbugs** [comment]
hmm... I don't fully understand the flow you're describing. `authorize_url` is supposed to be handled by the user agent (i.e., browser). if your flow doesn't involve a browser, you probably don't need the authorization code flow. either the client credentials grant or resource owner password grant is probably more appropriate. in any case, this doesn't sound like a bug or plausible feature enhancement for this library, so I'm going to go ahead and close this issue.

**Comment by hrbigelow** [comment]
ahh sorry for the vagueness.    i first ask the user to submit an email address, and send authorize_url as a link in that email.   however, authorize_url points to an endpoint on *my* server - an endpoint that will carry out the same functionality as https://accounts.google.com/o/oauth2/v2/auth, for example.

this flow basically delegates identity management to a generic "email owner", so doesn't require the user to have a facebook or google or github or other account in particular, just an email.

but, it means i need at least to implement that functionality of an Oauth server that issues an auth token.

**Comment by ramosbugs** [comment]
this crate implements the data structures involved in the protocol and can be used by an authorization server for serializing and deserializing the various data structures, but implementing an authorization server involves a lot more use-case-specific functionality than is possible for any general purpose library.
