### ISSUE TITLE
upgrade url crate to 2.x

### ISSUE THREAD

**Issue by legokichi** [ramosbugs/oauth2-rs#67]
https://github.com/seanmonstar/reqwest/issues/582

**Comment by ramosbugs** [comment]
I would welcome a PR to do this, though it'll need to be part of the current 3.x alpha series since it sounds like a breaking change for the external API.

**Comment by legokichi** [comment]
waiting reqwest 0.10.0 release...

**Comment by legokichi** [comment]
https://github.com/ramosbugs/oauth2-rs/pull/70
done
