### ISSUE TITLE
Re-export relevant structs from http crate

### ISSUE THREAD

**Issue by siku2** [ramosbugs/oauth2-rs#81]
This issue is referring to version `3.0.0-alpha.7`.

---

I was trying to use a custom http client function (namely [actix_web::client::Client](https://docs.rs/actix-web/2.0.0/actix_web/client/struct.Client.html)) and it turned out to be a lot more cumbersome than I was expecting.

The problem is constructing the [HttpResponse](https://docs.rs/oauth2/3.0.0-alpha.7/oauth2/struct.HttpResponse.html) struct as it contains structs from the http crate.
To use these structs one has to add the http crate to the dependencies first.
This itself isn't that big of a problem but the library pins version 0.1 and a lot of other crates (actix_web included) use version 0.2.

I'm not sure whether this is considered good practice, but [actix_web re-exports some items](https://docs.rs/actix-http/1.0.1/src/actix_http/lib.rs.html#49) from the http crate which makes it a lot easier to work with them.

It would be a lot easier to write custom http client functions if the crate re-exported the relevant http items (like [StatusCode](https://docs.rs/http/0.1.19/http/status/struct.StatusCode.html) and [HeaderMap](https://docs.rs/http/0.1.19/http/header/struct.HeaderMap.html)).

**Comment by ramosbugs** [comment]
Sounds reasonable
