### ISSUE TITLE
Add support for expiration time

### ISSUE THREAD

**Issue by FSMaxB-dooshop** [ramosbugs/oauth2-rs#84]
Looking at the current API (3.0.0-alpha.9) I couldn't find any expiration time (`expires_in`) for `AccessToken` or `RefreshToken`. This would be required for many types of application.

Would you be able to add this functionality to you API?

**Comment by ramosbugs** [comment]
`AccessToken` and `RefreshToken` are just wrapper types. `expires_in` is part of the token response: https://docs.rs/oauth2/3.0.0-alpha.9/oauth2/struct.StandardTokenResponse.html#method.set_expires_in

**Comment by FSMaxB-dooshop** [comment]
Oh, ok, thanks for pointing me in the right direction.
