### ISSUE TITLE
how can i set the value of redirect url to "postmessage" ? 

### ISSUE THREAD

**Issue by noelzubin** [ramosbugs/oauth2-rs#88]
I cant get oauth2 working for google with authorization code. According to this stackover answer. i need to set the redirectUrl to the literal string "postmessage". https://stackoverflow.com/questions/11485271/google-oauth-2-authorization-error-redirect-uri-mismatch

But  .set_redirect_url expects  a RedirectUrl which expects a Url.

`
Err 'value: RelativeUrlWithoutBase',
`

**Comment by noelzubin** [comment]
Figured it out.
instead of setting redirect uri using `.set_redirect_uri`. use the function `pub fn exchange_code_extension<T>` which takes i extra params. and  set redirect_uri as string there.

**Comment by ramosbugs** [comment]
https://github.com/ramosbugs/oauth2-rs/blob/master/examples/google.rs shows an example of how to integrate this crate with Google Sign-in. https://tools.ietf.org/html/rfc6749#section-3.1.2 states unequivocally that the `redirect_uri` must be an absolute URI, which `postmessage` is not. I'm not sure which sign-in flow you're trying to use, but this shouldn't be necessary...
