### ISSUE TITLE
Example for token.set_extra_fields?

### ISSUE THREAD

**Issue by PrismaPhonic** [ramosbugs/oauth2-rs#89]
I'm trying to integrate with Vimeo Oauth, which returns a user field with user info when it returns the access token. I imagine I can get this somehow from `token.extra_fields` (off of the `BasicTokenResponse`). I'm having trouble figuring out how to use the `set_extra_fields` method which I imagine I need to use to declare what the extra fields are that I want to grab? In this case, I want to get access to the `user` field on the retrieved token response.

**Comment by ramosbugs** [comment]
For access to additional fields in the token response, use a [`StandardTokenResponse`](https://docs.rs/oauth2/3.0.0-alpha.9/oauth2/struct.StandardTokenResponse.html) with the `EF` type argument set to a type you define (with the desired fields) that implements [`ExtraTokenFields`](https://docs.rs/oauth2/3.0.0-alpha.9/oauth2/trait.ExtraTokenFields.html).

Here's an example from the crate's unit tests: https://github.com/ramosbugs/oauth2-rs/blob/4b6fc619f4746ea6a5aa03efffdac9b1e4e27502/src/tests.rs#L1039

The fields are accessed via `extra_fields()`: https://github.com/ramosbugs/oauth2-rs/blob/4b6fc619f4746ea6a5aa03efffdac9b1e4e27502/src/tests.rs#L1143-L1144
